name: "Simple build"

# Triggers the workflow on push or pull request events
on: [push, pull_request]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore AzureDevOps.ReportingTool.sln"
      - name: 'dotnet test Reports'
        run: dotnet test --logger trx --no-build /p:CollectCoverage=true  /p:CoverletOutputFormat='opencover' /p:CoverletOutput=$(Build.SourcesDirectory)/coverage/reports/ /p:exclude=\"[Microsoft*]*,[xunit*]*\" test/AzureDevOps.Report.Unittest/AzureDevOps.Report.Unittest.csproj
      - name: 'dotnet test ReportTool'
        run: dotnet test --logger trx --no-build /p:CollectCoverage=true  /p:CoverletOutputFormat='opencover' /p:CoverletOutput=$(Build.SourcesDirectory)/coverage/reportingtool/ /p:exclude=\"[Microsoft*]*,[xunit*]*\" test/AzureDevOps.ReportingTool.Unittest/AzureDevOps.ReportingTool.Unittest.csproj
      - name: 'dotnet test Scanner'
        run: dotnet test --logger trx --no-build /p:CollectCoverage=true  /p:CoverletOutputFormat='opencover' /p:CoverletOutput=$(Build.SourcesDirectory)/coverage/scanner/ /p:exclude=\"[Microsoft*]*,[xunit*]*\" test/AzureDevOps.Scanner.Unittest/AzureDevOps.Scanner.Unittest.csproj